In [3]:
import torch
torch.__version__

c:\Users\2868201\OneDrive - TCS COM PROD\Desktop\pytorch\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


'2.12.0+cpu'

In [4]:
# scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# checking the dimensions of scalar
scalar.ndim

0

In [7]:
# retrieve the number from the scalar
scalar.item()

7

In [9]:
# vector: a single dimension tensor but can contain many numbers
vector = torch.tensor([7, 7]) # a tensor but with multiple values
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
# check shape of vector
vector.shape

torch.Size([2])

In [12]:
# matrix
MATRIX = torch.tensor([
    [7,8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
# checking dimensions
MATRIX.ndim

2

In [14]:
# shape of matrix
MATRIX.shape

torch.Size([2, 2])

In [15]:
# creating a tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [2,4,5]]
])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])