In [3]:
import torch
torch.__version__

c:\Users\2868201\OneDrive - TCS COM PROD\Desktop\pytorch\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


'2.12.0+cpu'

In [4]:
# scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# checking the dimensions of scalar
scalar.ndim

0

In [7]:
# retrieve the number from the scalar
scalar.item()

7

In [9]:
# vector: a single dimension tensor but can contain many numbers
vector = torch.tensor([7, 7]) # a tensor but with multiple values
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
# check shape of vector
vector.shape

torch.Size([2])

In [12]:
# matrix
MATRIX = torch.tensor([
    [7,8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
# checking dimensions
MATRIX.ndim

2

In [14]:
# shape of matrix
MATRIX.shape

torch.Size([2, 2])

In [15]:
# creating a tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [2,4,5]]
])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
# creating a tensor of random numbers of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype


(tensor([[5.9646e-01, 5.2895e-01, 2.4415e-01, 8.7407e-01],
         [9.0446e-01, 5.5122e-01, 6.6407e-01, 3.2765e-01],
         [8.7959e-02, 9.1536e-01, 3.0362e-01, 3.2544e-05]]),
 torch.float32)

In [20]:
# create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# sometimes we just want to fill tensors wil 0s and 1s.
# create tensors of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# create a tensor of all 1s
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
# creating a tensor with range of numbers
# start = 0, end= 10, step = 1
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

- Many types but some are cpu and gpu specific
- if we see `torch.cuda` anywhere, the tensor is being used for GPU 
- most common is `torch.float32` or `torch.float`, called as "32 bit floating point
- also available for 16 bit and 64 bit

- floats exist to do computing with precision.
- matter is DL and numerical computing as you are making so many operations, the more detail you have to calculate on, the more compute is used.

In [28]:
# default is float32
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
dtype = None,
device= None,
requires_grad = False) # if True, operations performed on the tensor are recorded.

float32_tensor.shape, float32_tensor.dtype, float32_tensor.ndim

(torch.Size([3]), torch.float32, 1)

In [29]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0],
dtype = torch.float16)
float16_tensor.dtype

torch.float16

In [30]:
# Details of the tensor
some_tensor = torch.rand(3,4)

# find out the details about it
print(some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"device tensor is stored on: {some_tensor.device}")


tensor([[0.0831, 0.4151, 0.0911, 0.2780],
        [0.3468, 0.4128, 0.4810, 0.7807],
        [0.6254, 0.1593, 0.0391, 0.9456]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


## Tensor Manipulation
- addition
- subtraction
- multiplication (element wise)
- division
- matrix multiplication

In [32]:
# create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10 # 10 gets added to every element

tensor([11, 12, 13])

In [33]:
tensor

tensor([1, 2, 3])

In [35]:
tensor = tensor - 10
tensor

tensor([-19, -18, -17])

In [37]:
# add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [39]:
# torch.mul() and torch.add() 
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
# element wise multiplication (each element multiplies its equivalent, index 0->0 , 1->1, 2->2, 3->3)
print(tensor, '*', tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


## Matrix Multiplication
One of the most common operations in ML and DL algos
Implemented by operation : `torch.matmul()`

### Rules for multiplication
- matrix ke inner dimensions should match. e.g. `(4,2), (2,4)`
- resultant matrix ke dimensions are outer dimensions: `(4,4)`

In [41]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [43]:
# element wise mul
tensor * tensor # [1*1, 2*2, 3*3]

tensor([1, 4, 9])

In [45]:
# matrix mul
torch.matmul(tensor, tensor)
# [1*1 + 2*2 + 3*3]

tensor(14)

In [46]:
# also can use @ for matmul
tensor @ tensor

tensor(14)

In [48]:
%%time
# matrix mul by hand
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 415 μs


tensor(14)

In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 83.2 μs


tensor(14)

## Common Errors in DL
TLDR: shape mismatches

In [50]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
# we can make mat mul work by making their inner dims match
# can do this using torch.transpose(input, dim0, dim1) or tensor.T

print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [53]:
# after transposing
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [54]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [55]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])